### ISSUE TITLE
Unicef-user_group table not getting populated properly

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#145]
**Describe the bug**
Dost-user_group table is not getting populated properly. No entry is being created for this group - Dost-Unsub-Users based on this flow - https://rapidpro.ilhasoft.in/flow/editor/c90153bd-961d-48b3-b847-1ae3070a24e7/

**To Reproduce**
Just run the flow for yourself, press 2, and see if the entry gets created.

**Expected behavior**
If users are added in this group, it should come in user_group table

**Comment by Satendra-SR** [comment]
Diagnosis on this

**Comment by Satendra-SR** [comment]
Tested it on staging and the table is being populated correctly.
Also, the records are being captured in the production as well. Here is the image showing such entries:
<img width="1102" alt="Screenshot 2021-08-09 at 2 30 33 PM" src="https://user-images.githubusercontent.com/39792899/128682684-47b2c3e3-87b7-416d-b979-90e9f43e4451.png">

**Comment by Satendra-SR** [comment]
@prtkdost 
I found some issue in the flow. Here are the details

1. The [Webhooks](https://rapidpro.ilhasoft.in/flow/editor/c90153bd-961d-48b3-b847-1ae3070a24e7/) set up has some issues, we need to split the Webhook section for unsubscribe users because for the unsubscribed users the variable `test` is not available which is available on the program selection route. So when a user is added to `Dost-unsub-group` then we need to add another webhook after that.
2. There are some entries available in the database for unsubscribed user group. This seems we are not removing the unsubscribed user from the unsub group if the user makes a missed call.

Let me know if you want me to make the changes in the first one.

**Comment by prtkdost** [comment]
@Satendra-SR there are some errors in this still.

The status in not getting updated properly. 

![image](https://user-images.githubusercontent.com/69189579/129341012-f6ca44de-02e5-4bb5-9bfb-ba758f2282f6.png)

Also, for these 2 groups, the users in group (both active and inactive) are much less than the users who picked up flows that were only scheduled for users in this group. [This](https://rapidpro.ilhasoft.in/flow/editor/d446495b-6a0e-4c95-ac2c-ec765005f6d2/) and [this](https://rapidpro.ilhasoft.in/flow/editor/85bf059c-a4d8-4606-aadf-51c4291e5f02/)

![image](https://user-images.githubusercontent.com/69189579/129341214-583f92e1-695f-475d-8bdc-07b19b7a0fab.png)

**Comment by Satendra-SR** [comment]
@prtkdost  

If a user is added to a group and the webhook is not called at that time, then the data related to that flow will not be captured for that user. And, according to the flow shown below, we can see that the user is removed before making the webhook call, due to which the system will not consider any change in the user group and will not update anything for that user. So we need to send webhook call whenever a user is added or removed from the group.
![image](https://user-images.githubusercontent.com/39792899/129521038-90a38c72-71c6-4e26-85ee-ccc763500ef5.png)

**Comment by Satendra-SR** [comment]
Check why the number is not correct for user groups.

**Comment by Satendra-SR** [comment]
The status of the user_group was not updating to inactive. So all the user_groups for a number were marked as `active`. Made the changes to mark the user_group as inactive.

**Comment by Satendra-SR** [comment]
This is deployed on production and working fine. Closing this now.
