### ISSUE TITLE
Load testing questions, discussions, approach and breakdown

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#481]
There were some questions related to load testing from Sindhuja - Added details here - https://www.notion.so/dosteducation/Load-Capacity-analysis-and-load-testing-in-RP-IVR-a89a4bc874a341399cb2bdecf4794fc9?pvs=4#2ee9d39f06c44159964bc6fce70437d7

**Comment by Satendra-SR** [comment]
As of May 2024 - Here are a few details related to 
1. The active users per system (Exotel and RapidPro)
2. The impact percentage of errors/exceptions



[Analysis of User_Data Impact in Both Applications Due to Exceptions (2).pdf](https://github.com/user-attachments/files/15529674/Analysis.of.User_Data.Impact.in.Both.Applications.Due.to.Exceptions.2.pdf)

**Comment by Sachinbisht27** [comment]
Closing as completed
